"""scripts/check_locks.py — the dev lock, the runtime lock, the inputs they
were compiled from and the installed venv must all agree.

Built after a rebuild on 2026-10-08 re-resolved the image's version ranges to
fastapi 0.143.0 while the tests kept running on 0.136.1: the new version's
built-in tracing took over every trace root and nothing in the gate could see
it, because the venv and the image resolved the same ranges independently.
"""
from scripts.check_locks import (
    interpreter_problems, lock_problems, parse_lock, stale_lock_problems,
)

DEV_LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.txt --universal --python-version 3.12 -o requirements.lock
fastapi==0.136.1
    # via -r requirements.txt
pywin32==311 ; sys_platform == 'win32'
    # via portalocker
starlette==1.0.0
    # via fastapi
"""

RUNTIME_LOCK = """\
fastapi==0.136.1
    # via
    #   -c requirements.lock
    #   -r requirements-runtime.txt
starlette==1.0.0
    # via fastapi
"""

INPUTS = "# API\nfastapi>=0.115,<1.0  # pinned by the lock\n"
INSTALLED = {"fastapi": "0.136.1", "starlette": "1.0.0"}
LINUX = {"sys_platform": "linux"}
IMAGE = {"sys_platform": "linux", "python_full_version": "3.12.15", "python_version": "3.12"}


def _problems(**overrides):
    args = dict(
        dev_lock=DEV_LOCK, runtime_lock=RUNTIME_LOCK, dev_inputs=INPUTS,
        runtime_inputs=INPUTS, installed=INSTALLED, environment=LINUX,
        image_environment=IMAGE,
    )
    args.update(overrides)
    return lock_problems(**args)


def test_a_consistent_set_reports_nothing():
    assert _problems() == []


def test_parse_lock_reads_pins_and_markers_and_skips_annotations():
    assert parse_lock(DEV_LOCK) == {
        "fastapi": [("0.136.1", "")],
        "pywin32": [("311", "sys_platform == 'win32'")],
        "starlette": [("1.0.0", "")],
    }


def test_runtime_pin_that_differs_from_the_dev_lock_is_reported():
    """The 2026-10-08 failure exactly: prod on one version, tests on another."""
    problems = _problems(runtime_lock=RUNTIME_LOCK.replace("fastapi==0.136.1", "fastapi==0.143.0"))
    assert len(problems) == 1
    assert "fastapi" in problems[0] and "0.143.0" in problems[0] and "0.136.1" in problems[0]


def test_runtime_package_the_dev_lock_lacks_is_reported():
    """The tests never ran with it, so a green suite says nothing about it."""
    problems = _problems(runtime_lock=RUNTIME_LOCK + "uvloop==0.21.0\n")
    assert len(problems) == 1 and "uvloop" in problems[0]


def test_input_requirement_with_no_pin_is_reported():
    problems = _problems(dev_inputs=INPUTS + "httpx>=0.28,<1.0\n")
    assert len(problems) == 1 and "httpx" in problems[0]


def test_input_requirement_the_pin_no_longer_satisfies_is_reported():
    """Someone raised a lower bound and forgot to re-lock."""
    problems = _problems(runtime_inputs="fastapi>=0.140,<1.0\n")
    assert len(problems) == 1 and "fastapi" in problems[0] and "0.136.1" in problems[0]


def test_installed_version_that_differs_from_the_lock_is_reported():
    problems = _problems(installed={**INSTALLED, "starlette": "1.7.0"})
    assert len(problems) == 1 and "starlette" in problems[0] and "1.7.0" in problems[0]


def test_locked_package_missing_from_the_venv_is_reported():
    problems = _problems(installed={"fastapi": "0.136.1"})
    assert len(problems) == 1 and "starlette" in problems[0]


def test_installed_package_the_lock_does_not_know_is_reported():
    """How fpdf2 went unnoticed: imported by clients/web/app.py, declared
    nowhere, present only because someone installed it by hand."""
    problems = _problems(installed={**INSTALLED, "fpdf2": "2.8.7"})
    assert len(problems) == 1 and "fpdf2" in problems[0]


def test_a_pin_for_another_platform_is_not_required_here():
    """pywin32 is locked for Windows; a Linux or Mac venv must not need it."""
    assert "pywin32" not in " ".join(_problems())
    problems = _problems(environment={"sys_platform": "win32"})
    assert len(problems) == 1 and "pywin32" in problems[0]


def test_names_compare_normalised():
    """PEP 503: the lock writes `opentelemetry-sdk`, metadata may say
    `opentelemetry_sdk` — the same distribution, never a mismatch."""
    dev = DEV_LOCK + "opentelemetry-sdk==1.41.1\n    # via -r requirements.txt\n"
    installed = {**INSTALLED, "OpenTelemetry_SDK": "1.41.1"}
    assert _problems(dev_lock=dev, installed=installed) == []


# --- review round, 2026-10-08: the holes a reviewer found by mutation ---------

SPLIT = """\
numpy==1.26.4 ; python_full_version < '3.13'
    # via -r requirements.txt
numpy==2.5.3 ; python_full_version >= '3.13'
    # via -r requirements.txt
"""
PY312 = {"sys_platform": "linux", "python_full_version": "3.12.7", "python_version": "3.12"}


def test_a_package_locked_twice_is_checked_against_the_entry_that_applies():
    """--universal with --python-version 3.12 is a LOWER bound, so uv may pin one
    package twice under disjoint markers. Keyed by name, the 3.13 entry silently
    replaced the 3.12 one and a venv holding numpy 0.0.1 passed."""
    problems = _problems(dev_lock=DEV_LOCK + SPLIT, installed={**INSTALLED, "numpy": "0.0.1"},
                         environment=PY312)
    assert len(problems) == 1
    assert "numpy" in problems[0] and "1.26.4" in problems[0] and "0.0.1" in problems[0]


def test_a_package_locked_twice_is_clean_when_the_right_version_is_installed():
    assert _problems(dev_lock=DEV_LOCK + SPLIT, installed={**INSTALLED, "numpy": "1.26.4"},
                     environment=PY312) == []


def test_a_lock_line_it_cannot_read_is_reported_not_skipped():
    problems = _problems(runtime_lock=RUNTIME_LOCK + "mystery @ https://example.com/m.whl\n")
    assert len(problems) == 1 and "mystery" in problems[0]


def test_an_installed_package_whose_pin_is_for_another_platform_is_reported():
    """tzdata pinned only for win32, yet installed here at whatever version: the
    lock vouches for nothing about it."""
    dev = DEV_LOCK + "tzdata==2025.2 ; sys_platform == 'win32'\n    # via pandas\n"
    problems = _problems(dev_lock=dev, installed={**INSTALLED, "tzdata": "1999.1"})
    assert len(problems) == 1 and "tzdata" in problems[0]


def test_venv_and_image_resolving_one_package_differently_is_reported():
    """Tests on one version, production on another — through a marker this time."""
    split = "foo==1.0 ; sys_platform == 'darwin'\nfoo==2.0 ; sys_platform == 'linux'\n"
    problems = _problems(dev_lock=DEV_LOCK + split, runtime_lock=RUNTIME_LOCK + split,
                         installed={**INSTALLED, "foo": "1.0"}, environment={"sys_platform": "darwin"})
    assert len(problems) == 1 and "foo" in problems[0] and "2.0" in problems[0]


def test_runtime_inputs_are_checked_against_the_runtime_lock():
    """A dev-only package declared for the image must be caught even though the
    dev lock has it — the python-multipart / instrumentor shape in CLAUDE.md."""
    problems = _problems(dev_lock=DEV_LOCK + "chainlit==2.9.0\n", installed={**INSTALLED, "chainlit": "2.9.0"},
                         runtime_inputs=INPUTS + "chainlit>=2.0,<3.0\n")
    assert len(problems) == 1 and "requirements-runtime.lock" in problems[0] and "chainlit" in problems[0]


def test_an_input_line_it_does_not_support_is_reported_not_raised():
    problems = _problems(runtime_inputs="-r requirements.txt\n" + INPUTS)
    assert len(problems) == 1 and "-r requirements.txt" in problems[0]


def test_a_different_minor_python_fails_and_a_different_patch_is_a_note():
    """3.13 tests against a 3.12 image prove little — fail. A patch behind is
    worth knowing but not blocking: uv's builds can lag the image's (on
    2026-10-08 uv offered 3.12.14 while the image ran 3.12.15)."""
    assert interpreter_problems("3.12.15", "3.12.15") == ([], [])
    problems, notes = interpreter_problems("3.13.1", "3.12.15")
    assert len(problems) == 1 and "3.13.1" in problems[0] and notes == []
    problems, notes = interpreter_problems("3.12.7", "3.12.15")
    assert problems == [] and len(notes) == 1 and "3.12.7" in notes[0] and "3.12.15" in notes[0]


def test_a_lock_that_recompiles_differently_is_stale():
    """Pins checked by name and version miss an added extra or a removed input;
    the locks reproduce exactly, so re-locking and comparing catches both."""
    fresh = DEV_LOCK + "socksio==1.0.0\n    # via httpx\n"
    problems = stale_lock_problems("requirements.lock", DEV_LOCK, fresh)
    assert len(problems) == 1 and "socksio" in problems[0]
    assert stale_lock_problems("requirements.lock", DEV_LOCK, DEV_LOCK) == []


def test_one_version_under_different_markers_is_not_a_disagreement():
    """colorama: Windows-only in the runtime lock, unconditional in the dev lock
    because a dev-only package needs it everywhere. Same version — fine."""
    dev = DEV_LOCK + "colorama==0.4.6\n    # via pytest\n"
    runtime = RUNTIME_LOCK + "colorama==0.4.6 ; sys_platform == 'win32'\n    # via click\n"
    assert _problems(dev_lock=dev, runtime_lock=runtime, installed={**INSTALLED, "colorama": "0.4.6"}) == []
