"""scripts/check_locks.py — the dev lock, the runtime lock, the inputs they
were compiled from and the installed venv must all agree.

Built after a rebuild on 2026-10-08 re-resolved the image's version ranges to
fastapi 0.143.0 while the tests kept running on 0.136.1: the new version's
built-in tracing took over every trace root and nothing in the gate could see
it, because the venv and the image resolved the same ranges independently.
"""
from scripts.check_locks import lock_problems, parse_lock

DEV_LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.txt --universal --python-version 3.12 -o requirements.lock
fastapi==0.136.1
    # via -r requirements.txt
pywin32==311 ; sys_platform == 'win32'
    # via portalocker
starlette==1.0.0
    # via fastapi
"""

RUNTIME_LOCK = """\
fastapi==0.136.1
    # via
    #   -c requirements.lock
    #   -r requirements-runtime.txt
starlette==1.0.0
    # via fastapi
"""

INPUTS = "# API\nfastapi>=0.115,<1.0  # pinned by the lock\n"
INSTALLED = {"fastapi": "0.136.1", "starlette": "1.0.0"}
LINUX = {"sys_platform": "linux"}


def _problems(**overrides):
    args = dict(
        dev_lock=DEV_LOCK, runtime_lock=RUNTIME_LOCK, dev_inputs=INPUTS,
        runtime_inputs=INPUTS, installed=INSTALLED, environment=LINUX,
    )
    args.update(overrides)
    return lock_problems(**args)


def test_a_consistent_set_reports_nothing():
    assert _problems() == []


def test_parse_lock_reads_pins_and_markers_and_skips_annotations():
    assert parse_lock(DEV_LOCK) == {
        "fastapi": ("0.136.1", ""),
        "pywin32": ("311", "sys_platform == 'win32'"),
        "starlette": ("1.0.0", ""),
    }


def test_runtime_pin_that_differs_from_the_dev_lock_is_reported():
    """The 2026-10-08 failure exactly: prod on one version, tests on another."""
    problems = _problems(runtime_lock=RUNTIME_LOCK.replace("fastapi==0.136.1", "fastapi==0.143.0"))
    assert len(problems) == 1
    assert "fastapi" in problems[0] and "0.143.0" in problems[0] and "0.136.1" in problems[0]


def test_runtime_package_the_dev_lock_lacks_is_reported():
    """The tests never ran with it, so a green suite says nothing about it."""
    problems = _problems(runtime_lock=RUNTIME_LOCK + "uvloop==0.21.0\n")
    assert len(problems) == 1 and "uvloop" in problems[0]


def test_input_requirement_with_no_pin_is_reported():
    problems = _problems(dev_inputs=INPUTS + "httpx>=0.28,<1.0\n")
    assert len(problems) == 1 and "httpx" in problems[0]


def test_input_requirement_the_pin_no_longer_satisfies_is_reported():
    """Someone raised a lower bound and forgot to re-lock."""
    problems = _problems(runtime_inputs="fastapi>=0.140,<1.0\n")
    assert len(problems) == 1 and "fastapi" in problems[0] and "0.136.1" in problems[0]


def test_installed_version_that_differs_from_the_lock_is_reported():
    problems = _problems(installed={**INSTALLED, "starlette": "1.7.0"})
    assert len(problems) == 1 and "starlette" in problems[0] and "1.7.0" in problems[0]


def test_locked_package_missing_from_the_venv_is_reported():
    problems = _problems(installed={"fastapi": "0.136.1"})
    assert len(problems) == 1 and "starlette" in problems[0]


def test_installed_package_the_lock_does_not_know_is_reported():
    """How fpdf2 went unnoticed: imported by clients/web/app.py, declared
    nowhere, present only because someone installed it by hand."""
    problems = _problems(installed={**INSTALLED, "fpdf2": "2.8.7"})
    assert len(problems) == 1 and "fpdf2" in problems[0]


def test_a_pin_for_another_platform_is_not_required_here():
    """pywin32 is locked for Windows; a Linux or Mac venv must not need it."""
    assert "pywin32" not in " ".join(_problems())
    problems = _problems(environment={"sys_platform": "win32"})
    assert len(problems) == 1 and "pywin32" in problems[0]


def test_names_compare_normalised():
    """PEP 503: the lock writes `opentelemetry-sdk`, metadata may say
    `opentelemetry_sdk` — the same distribution, never a mismatch."""
    dev = DEV_LOCK + "opentelemetry-sdk==1.41.1\n    # via -r requirements.txt\n"
    installed = {**INSTALLED, "OpenTelemetry_SDK": "1.41.1"}
    assert _problems(dev_lock=dev, installed=installed) == []
