"""Build skills/contract_review/playbook/ from the legal-team source materials.

Inputs (canonical, hand-authored by legal — do not edit):
  data/contract_review_skills/Trinetix_Contract_Playbook_2026.docx
  data/contract_review_skills/<Type> Review Skill/SKILL.md
  data/contract_review_skills/NDA Review Skill/references/shared_operating_rules.md
  data/contract_review_skills/NDA Review Skill/references/no_signature_checklist.md

Outputs (generated — committed for audit / clean diffs):
  skills/contract_review/playbook/global/*.md
  skills/contract_review/playbook/{nda,msa,sow,baa}/{SKILL.md, playbook_matrix.md}
  docs/playbook_cross_reference.md

Idempotent: re-running on the same inputs produces byte-identical files.

Run:
  uv run python scripts/build_playbook.py

See docs/playbook_cross_reference.md for which file owns which concern.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn


ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "data" / "contract_review_skills"
PLAYBOOK_DOCX = SRC_DIR / "Trinetix_Contract_Playbook_2026.docx"
OUT_DIR = ROOT / "skills" / "contract_review" / "playbook"
DOCS_DIR = ROOT / "docs"

# Playbook table indices — derived from the .docx structure (see body dump in
# scripts/build_playbook.py header docs). If legal reorders sections, this
# constant updates; nothing else should.
TABLE_INDEX = {
    "core_principles": 0,        # 11x2 Principle | Rule
    "risk_ratings": 1,           # 5x3 Rating | Meaning | Default action
    "escalation": 2,             # 7x2 Escalate to | When
    "contract_selection": 3,     # 8x3 Scenario | Document | Checks
    "msa_matrix": 4,             # 29x6
    "sow_matrix": 5,             # 17x6
    "nda_matrix": 6,             # 12x6
    "baa_matrix": 7,             # 13x6
    "approval_matrix": 8,        # 11x3
    "clause_bank": 9,            # 8x3
    "external_examples": 10,     # 7x2
}

# Headings (Heading 1) that bracket Section 10 (AI Review Procedure) in the docx.
AI_PROC_START = "10. AI Review Procedure"
AI_PROC_END = "11. Clause Bank Naming Convention"

TYPES = ("nda", "msa", "sow", "baa")
TYPE_TO_FOLDER = {
    "nda": "NDA Review Skill",
    "msa": "MSA Review Skill",
    "sow": "SOW Review Skill",
    "baa": "BAA Review Skill",
}
TYPE_TO_MATRIX_TABLE = {
    "nda": "nda_matrix",
    "msa": "msa_matrix",
    "sow": "sow_matrix",
    "baa": "baa_matrix",
}

GENERATED_NOTICE = (
    "<!-- GENERATED by scripts/build_playbook.py — do not hand-edit. -->\n"
    "<!-- Source: data/contract_review_skills/. Re-run the script to update. -->\n\n"
)


def _md_escape_cell(s: str) -> str:
    """Make a cell safe for a markdown table row."""
    return s.replace("|", "\\|").replace("\n", "<br>").strip()


def _table_to_markdown(table) -> str:
    """Render a python-docx table as a GFM markdown table."""
    rows = table.rows
    if not rows:
        return ""
    header = [_md_escape_cell(c.text) for c in rows[0].cells]
    sep = ["---"] * len(header)
    body_rows = []
    for row in rows[1:]:
        cells = [_md_escape_cell(c.text) for c in row.cells]
        # Pad if a row has fewer cells than the header (defensive).
        while len(cells) < len(header):
            cells.append("")
        body_rows.append("| " + " | ".join(cells) + " |")
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(sep) + " |"]
    lines.extend(body_rows)
    return "\n".join(lines) + "\n"


def _extract_sections(text: str) -> dict[str, str]:
    """Split a markdown doc by `## ` headings; return {heading_text: section_body}.

    Section body excludes the heading line; trailing whitespace stripped.
    """
    sections: dict[str, str] = {}
    matches = list(re.finditer(r"^##\s+(.+)$", text, re.M))
    for i, m in enumerate(matches):
        name = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        sections[name] = text[start:end].strip()
    return sections


def _render_ai_review_procedure(doc) -> str:
    """Render Section 10 (AI Review Procedure) — paragraphs + headings + bullets — as markdown."""
    para_map = {p._element: p for p in doc.paragraphs}
    in_section = False
    out: list[str] = []
    for element in doc.element.body:
        if element.tag != qn("w:p"):
            continue
        p = para_map.get(element)
        if p is None:
            continue
        text = p.text.strip()
        if not text:
            continue
        style = p.style.name if p.style else ""
        if style == "Heading 1":
            if text == AI_PROC_START:
                in_section = True
                continue  # heading itself becomes the file title
            if text == AI_PROC_END:
                break
        if not in_section:
            continue
        if style == "Heading 2":
            out.append(f"\n### {text}\n")
        elif style == "List Bullet":
            out.append(f"- {text}")
        else:
            # Normal paragraph. The docx uses `\n` for soft breaks inside one paragraph
            # (e.g. the issue-list schema). Preserve them as blank-line-separated lines
            # so markdown renders them as separate output-schema fields rather than
            # one continuous paragraph.
            out.append(text.replace("\n", "  \n"))
            out.append("")  # blank line between paragraphs
    return "\n".join(out).strip() + "\n"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write(path: Path, content: str) -> bool:
    """Write content if changed. Returns True if file was created or modified."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _clean_dir(d: Path) -> None:
    """Remove every .md under d (recursively) so removed inputs don't linger."""
    if not d.exists():
        return
    for p in d.rglob("*.md"):
        p.unlink()


def _build_global_files(doc, sections: dict[str, str], no_sig_checklist: str) -> dict[str, str]:
    """Build the global/*.md files. Returns {filename: content} (not yet written)."""
    files: dict[str, str] = {}

    # role_and_golden_rules.md — canonical: shared_operating_rules.md
    files["role_and_golden_rules.md"] = (
        GENERATED_NOTICE
        + "# Role and Golden Rules\n\n"
        + "## Role\n\n" + sections["Role"] + "\n\n"
        + "## Golden Rules\n\n" + sections["Golden rules"] + "\n"
    )

    # core_principles.md — canonical: playbook Table 0
    files["core_principles.md"] = (
        GENERATED_NOTICE
        + "# Core Contracting Principles\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["core_principles"]])
    )

    # risk_rating.md — canonical: playbook Tables 1 + 2
    files["risk_rating.md"] = (
        GENERATED_NOTICE
        + "# Risk Rating and Escalation\n\n"
        + "## Risk Ratings\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["risk_ratings"]])
        + "\n## Escalation Owners\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["escalation"]])
    )

    # approval_matrix.md — canonical: playbook Table 8
    files["approval_matrix.md"] = (
        GENERATED_NOTICE
        + "# Approval Matrix\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["approval_matrix"]])
    )

    # output_format.md — canonical: shared_operating_rules.md
    files["output_format.md"] = (
        GENERATED_NOTICE
        + "# Required Final Output Format\n\n"
        + sections["Required final output format"] + "\n"
    )

    # ai_review_procedure.md — canonical: playbook §10
    files["ai_review_procedure.md"] = (
        GENERATED_NOTICE
        + "# AI Review Procedure\n\n"
        + _render_ai_review_procedure(doc)
    )

    # external_comments.md — canonical: rules from references, examples from playbook Table 10
    files["external_comments.md"] = (
        GENERATED_NOTICE
        + "# External Comment Rules and Examples\n\n"
        + "## Rules\n\n" + sections["External comment rules"] + "\n\n"
        + "## Examples\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["external_examples"]])
    )

    # contract_selection.md — canonical: playbook Table 3
    files["contract_selection.md"] = (
        GENERATED_NOTICE
        + "# Contract Selection Matrix\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["contract_selection"]])
    )

    # clause_bank.md — canonical: playbook Table 9
    files["clause_bank.md"] = (
        GENERATED_NOTICE
        + "# Clause Bank Naming Convention\n\n"
        + "Use these stable IDs when referring to fallback language.\n\n"
        + _table_to_markdown(doc.tables[TABLE_INDEX["clause_bank"]])
    )

    # no_signature_checklist.md — canonical: team's no_signature_checklist.md (verbatim)
    files["no_signature_checklist.md"] = GENERATED_NOTICE + no_sig_checklist.strip() + "\n"

    return files


def _build_type_files(doc, contract_type: str) -> dict[str, str]:
    """Build playbook/<type>/{SKILL.md, playbook_matrix.md}."""
    folder = SRC_DIR / TYPE_TO_FOLDER[contract_type]
    skill_md = _read(folder / "SKILL.md")
    matrix_md = _table_to_markdown(doc.tables[TABLE_INDEX[TYPE_TO_MATRIX_TABLE[contract_type]]])
    matrix_doc = (
        GENERATED_NOTICE
        + f"# {contract_type.upper()} Playbook Matrix\n\n"
        + "Reference table from the Trinetix Contract Playbook. Use these as the "
        + "deterministic clause-by-clause ceiling alongside the per-type SKILL.md.\n\n"
        + matrix_md
    )
    return {
        "SKILL.md": GENERATED_NOTICE + skill_md.strip() + "\n",
        "playbook_matrix.md": matrix_doc,
    }


def _build_cross_reference() -> str:
    """Generate docs/playbook_cross_reference.md — the maintained crosswalk."""
    return (
        GENERATED_NOTICE
        + "# Playbook Cross-Reference\n\n"
        + "Where each concern lives across the three legal-team source artifacts, "
        + "which one we treat as canonical when they overlap, and how the build script "
        + "extracts it into `skills/contract_review/playbook/`.\n\n"
        + "**Sources:**\n"
        + "- `data/contract_review_skills/Trinetix_Contract_Playbook_2026.docx` — the playbook (90% tables).\n"
        + "- `data/contract_review_skills/<Type> Review Skill/SKILL.md` — per-type skill (NDA, MSA, SOW, BAA).\n"
        + "- `data/contract_review_skills/NDA Review Skill/references/shared_operating_rules.md` — shared role/rules/output format (identical copy in each type folder).\n\n"
        + "| Concern | Playbook | SKILL.md | References | Canonical | Bundle file |\n"
        + "| --- | --- | --- | --- | --- | --- |\n"
        + "| Role | — | — | ✅ Role | references | global/role_and_golden_rules.md |\n"
        + "| Golden rules | — | mentioned | ✅ Golden rules | references | global/role_and_golden_rules.md |\n"
        + "| Risk ratings | ✅ Table 1 | mentioned | ✅ Risk ratings | **playbook** | global/risk_rating.md |\n"
        + "| Approval owners | ✅ Table 2 + Table 8 | mentioned | ✅ Approval owners | **playbook** | global/risk_rating.md + global/approval_matrix.md |\n"
        + "| Approval matrix | ✅ Table 8 | — | — | playbook only | global/approval_matrix.md |\n"
        + "| Core principles | ✅ Table 0 | — | — | playbook only | global/core_principles.md |\n"
        + "| Contract selection matrix | ✅ Table 3 | — | — | playbook only | global/contract_selection.md |\n"
        + "| AI Review Procedure | ✅ §10 | implicit | — | playbook | global/ai_review_procedure.md |\n"
        + "| Clause-bank naming | ✅ Table 9 | — | — | playbook | global/clause_bank.md |\n"
        + "| External-comment rules + examples | ✅ Table 10 (examples) | — | ✅ External comment rules | rules: references / examples: playbook | global/external_comments.md |\n"
        + "| No-Signature Gate | mentioned | ✅ section | ✅ no_signature_checklist.md | **references** | global/no_signature_checklist.md |\n"
        + "| Required output format | — | refers to references | ✅ Required final output format | **references** | global/output_format.md |\n"
        + "| Per-type Source Position | implicit | ✅ Source position | — | SKILL.md | `<type>/SKILL.md` |\n"
        + "| Per-type Inputs to request | — | ✅ Inputs | — | SKILL.md | `<type>/SKILL.md` |\n"
        + "| Per-type Clause review rules | — | ✅ Clause review rules | — | SKILL.md | `<type>/SKILL.md` |\n"
        + "| Per-type Clause matrix | ✅ Tables 4–7 | — | — | playbook only | `<type>/playbook_matrix.md` |\n"
        + "| Per-type Review workflow | mentioned in §10 | ✅ Review workflow | — | SKILL.md | `<type>/SKILL.md` |\n"
        + "| Per-type Quality-control checklist | — | ✅ Quality control checklist | — | SKILL.md | `<type>/SKILL.md` |\n"
        + "| Test prompt | — | — | ✅ test_prompt.md | references | not in bundle (used for smoke tests) |\n\n"
        + "## Reading the table\n\n"
        + "Cells with checkmarks in **multiple columns** are reconciliation points — the canonical column says which source the build script extracts from so the bundle never carries two conflicting versions of the same rule.\n\n"
        + "## Bundle assembly order\n\n"
        + "`skills/base.py::load_bundle(contract_type)` concatenates these in the order defined by `BUNDLE_ORDER`:\n\n"
        + "1. `global/role_and_golden_rules.md`\n"
        + "2. `global/core_principles.md`\n"
        + "3. `global/risk_rating.md`\n"
        + "4. `global/approval_matrix.md`\n"
        + "5. `global/output_format.md`\n"
        + "6. `global/ai_review_procedure.md`\n"
        + "7. `global/external_comments.md`\n"
        + "8. `global/contract_selection.md`\n"
        + "9. `global/clause_bank.md`\n"
        + "10. `<type>/SKILL.md`\n"
        + "11. `<type>/playbook_matrix.md`\n"
        + "12. `global/no_signature_checklist.md`\n\n"
        + "Order rationale: role → guiding principles → scoring vocabulary → output spec → procedure → external comments → catalogue → per-type rules → gate (read last by the model so it's the most-recent instruction before output).\n"
    )


def main() -> int:
    if not PLAYBOOK_DOCX.exists():
        print(f"ERROR: {PLAYBOOK_DOCX} not found", file=sys.stderr)
        return 1

    doc = Document(PLAYBOOK_DOCX)
    shared_ops = _read(SRC_DIR / "NDA Review Skill" / "references" / "shared_operating_rules.md")
    sections = _extract_sections(shared_ops)
    no_sig = _read(SRC_DIR / "NDA Review Skill" / "references" / "no_signature_checklist.md")

    # Wipe and regenerate playbook/ — keeps deletes / renames honest.
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    written = 0

    # global/
    global_files = _build_global_files(doc, sections, no_sig)
    for name, content in global_files.items():
        _write(OUT_DIR / "global" / name, content)
        written += 1

    # per-type
    for t in TYPES:
        type_files = _build_type_files(doc, t)
        for name, content in type_files.items():
            _write(OUT_DIR / t / name, content)
            written += 1

    # docs/playbook_cross_reference.md
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    _write(DOCS_DIR / "playbook_cross_reference.md", _build_cross_reference())

    print(f"build_playbook.py: wrote {written} bundle files + cross-reference")
    print(f"  global/: {len(global_files)} files")
    print(f"  per-type: {len(TYPES)} folders, {2 * len(TYPES)} files")
    print(f"  cross-reference: docs/playbook_cross_reference.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
